version: '3.5'

services:
  aenaeri-app-frontend:
    build: 
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/home/app/appDir/src
      - ./package.json:/home/app/appDir/package.json
      - ./tsconfig.json:/home/app/appDir/tsconfig.json
      - ./public:/home/app/appDir/public
      - ./vite.config.ts:/home/app/appDir/vite.config.ts
      - node_modules:/home/app/appDir/node_modules
    depends_on:
      - aenaeri-app-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://aenaeri-app:password123@postgres/aenaeri-app
      - MONGO_URI=mongodb://aenaeri-app:password123@mongo/aenaeri-app
      - SECRET=acdcabbacd
      - DEV_USER_NAME=ile
    networks:
      - backend
    command: npm run-script start-frontend
  
  aenaeri-app-backend:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/home/app/appDir/server
      - ./package.json:/home/app/appDir/package.json
      - node_modules:/home/app/appDir/node_modules
    depends_on:
      - postgres
      - mongo
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://aenaeri-app:password123@postgres/aenaeri-app
      - MONGO_URI=mongodb://aenaeri-app:password123@mongo/aenaeri-app
      - SECRET=acdcabbacd
      - DEV_USER_NAME=ile
    networks:
      - backend
    command: npm run-script start-backend


  postgres:
    image: 'postgres:12.8'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aenaeri-app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=aenaeri-app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    logging:
      driver: 'none'
  mongo:
    image: 'mongo'
    restart: unless-stopped
    container_name: 'aenaeri-app-mongo'
    environment:
      - MONGO_INITDB_DATABASE=aenaeri-app
      - MONGO_INITDB_ROOT_USERNAME=aenaeri-app
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./init-dev-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
    logging:
      driver: 'none'
    command: --quiet
 
networks:
  backend:

volumes:
  node_modules:
