version: '3.5'

services:
  aenaeri-app:
    build: .
    ports:
      - "3001:3001"
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app/appDir
    depends_on:
      - postgres
      - mongo
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://aenaeri-app:password123@postgres/aenaeri-app
      - MONGO_URI=mongodb://aenaeri-app:password123@mongo/aenaeri-app
      - SECRET=acdcabbacd
    networks:
      - backend
    command: npm run dev
  postgres:
    image: 'postgres:11.5'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aenaeri-app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=aenaeri-app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  mongo:
    image: 'mongo'
    container_name: 'aenaeri-app-mongo'
    environment:
      - MONGO_INITDB_DATABASE=aenaeri-app
      - MONGO_INITDB_ROOT_USERNAME=aenaeri-app
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./init-dev-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend

networks:
  backend: