version: '3.5'

services:
  aenaeri-app:
    build: .
    ports:
      - "3001:3001"
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app/appDir
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://aenaeri-app:password123@postgres/aenaeri-app
      - SECRET=acdcabbacd
    networks:
      - backend
    command: npm run dev
  postgres:
    image: 'postgres:11.5'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aenaeri-app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=aenaeri-app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend: