import * as mongoose from 'mongoose';
import { SchemaTypes } from 'mongoose';

export const BoxScorePlayerSchema = new mongoose.Schema({
    person: {
        id: Number,
        fullName: String,
        link: String,
        shootsCatches: String,
        rosterStatus: String,
    },
    jerseyNumber: String,
    position: {
        code: SchemaTypes.Mixed,
        name: SchemaTypes.Mixed,
        type: SchemaTypes.Mixed,
        abbreviation: String,
    },
    stats: {
        skaterStats: {
            timeOnIce: String,
            assists: Number,
            goals: Number,
            shots: Number,
            hits: Number,
            powerPlayGoals: Number,
            powerPlayAssists: Number,
            penaltyMinutes: Number,
            faceOffWins: Number,
            faceoffTaken: Number,
            takeaways: Number,
            giveaways: Number,
            shortHandedGoals: Number,
            shortHandedAssists: Number,
            blocked: Number,
            plusMinus: Number,
            evenTimeOnIce: String,
            powerPlayTimeOnIce: String,
            shortHandedTimeOnIce: String,
        },
        goalieStats: {
            timeOnIce: String,
            assists: Number,
            goals: Number,
            pim: Number,
            shots: Number,
            saves: Number,
            powerPlaySaves: Number,
            shortHandedSaves: Number,
            evenSaves: Number,
            shortHandedShotsAgainst: Number,
            evenShotsAgainst: Number,
            powerPlayShotsAgainst: Number,
            decision: String,
            savePercentage: Number,
            powerPlaySavePercentage: Number,
            evenStrengthSavePercentage: Number,
        },
    },
});
